### PR TITLE
Use Boxx version for Wasmer update message

### PR DESCRIPTION
**Pull request by syrusakbary**
It seems [Boxx](https://crates.io/crates/boxx) can help us simplify a bit the codebase... so it seems like a great tradeoff!

Great work on the package @EverlastingBugstopper 🎉

### CODE REVIEW

**Comment by EverlastingBugstopper** [comment]
Nice! Glad you find it useful 😄

If you want to keep the same style as the current code, you can do something like Boxx::builder().border_style(BorderStyle::Round).build().display(msg);

**Comment by syrusakbary** [comment]
@EverlastingBugstopper after trying it a bit more, it seems the box layout is having some issues (see screenshot):

Screen Shot 2020-02-18 at 10 39 11 AM

If you want to try it locally, you can:

```bash
git clone https://github.com/wasmerio/wapm-cli.git
cd wapm-cli

# Build with the update notification feature
cargo build --features=update-notifications

./target/debug/wapm run-background-update-check
# This should show the box!
WAPM_FORCE_UPDATE_NOTIFICATION=1 ./target/debug/wapm run asdf
```

**Comment by syrusakbary** [comment]
I think the issue is due the coloring of some text in the terminal.

Note: you can use a similar function to the following (implemented in js) to clean ansi characters from the text (so you can get the real length of a text).

```js
/**
  This function removes the ansi escape characters
  (normally used for printing colors and so)
  Inspired by: https://github.com/chalk/ansi-regex/blob/master/index.js
  MIT License Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)
 */
const cleanStdout = (stdout) => {
  const pattern = [
    "[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[-a-zA-Z\\d\\/#&.:=?%@~_]*)*)?\\u0007)",
    "(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PR-TZcf-ntqry=><~]))"
  ].join("|");

  const regexPattern = new RegExp(pattern, "g");
  return stdout.replace(regexPattern, "");
};
```

**Comment by MarkMcCaskey** [comment]
Following up, I just searched crates.io and found https://crates.io/crates/strip-ansi-escapes ; hasn't been updated in 2 years but seems widely used.  This is my first time seeing it, but could be exactly what we need!

**Comment by syrusakbary** [comment]
It works like a charm with the latest version of `boxx` (`0.0.2-beta`). Thanks for the fix @EverlastingBugstopper!

Screen Shot 2020-02-28 at 11 43 58 AM

**Comment by EverlastingBugstopper** [comment]
Awesome! Happy to help, let me know if you see any other issues or have comments on ways documentation/the API could be better 😁

**Comment by EverlastingBugstopper** [comment]
Hey y'all - I think I'm going to take this out of beta (no 1.0 yet though) but I want to rename it to `Billboard` because I think it gets the point across better and is the naming isn't driven by limitations around Rust keywords. Any objections?

**Pull request merged**
