### PR TITLE
add ability to use a proxy

### LINKED ISSUE #134: Proxy support
Thanks for proposing a new feature!

### Motivation

Most people work behind corporate proxy

### Proposed solution

Expose use of reqwest proxy into cli

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
it's untested!

resolves #134

### CODE REVIEW

**Comment by zicklag** [comment]
Thanks for this!

It looks like it might be working, but it doesn't ready the proxy credentials from the url: `http://user:pass@192.168.1.2:3128` so I get a `Error: https://registry.wapm.io/graphql: error trying to connect: proxy authentication required`.

Also it would be nice if it read the `http_proxy` environment variable instead of the `WAPM_PROXY_URL` because that is standard across most Linux applications and it would then work on systems that already have that set without any extra configuration.

**Comment by MarkMcCaskey** [comment]
Okay!  I'm parsing the URL now and look at `ALL_PROXY`, `HTTPS_PROXY`, and `http_proxy` environment variables.

Hopefully that works!  I'll set up a proxy and try to test it in the afternoon when I'm more tired, for now I'm going to use my energy on some other tasks.

Thanks for the feedback!

**Comment by mmacedoeu** [comment]
Works for me using config set

**Comment by zicklag** [comment]
It worked! My only thought is that it seems like the `HTTPS_PROXY` env var should be lowercase like `http_proxy`. In my experience, some programs will respect both the uppercase and the lowercase, while other programs will only respect the lowercase version, so in my environment I just set the lowercase version and that works for the majority of software that has support for proxies.

**Comment by MarkMcCaskey** [comment]
> It worked! My only thought is that it seems like the `HTTPS_PROXY` env var should be lowercase like `http_proxy`. In my experience, some programs will respect both the uppercase and the lowercase, while other programs will only respect the lowercase version, so in my environment I just set the lowercase version and that works for the majority of software that has support for proxies.

Thanks!

Yeah, I think I just saw that in whatever docs I was reading.  I'll do another pass and make sure we're following standards.  Though supporting both ways seems like an easy improvement to UX, so we'll probably just do that.

**Comment by zicklag** [comment]
Sounds good to me.

**Pull request merged**
